# Generated by Django 4.0.3 on 2022-04-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='enddate',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='percentnextmonth',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='percentthismonth',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='promodiscount',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='promotype',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='promovolume',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='startdate',
            name='pub_date',
        ),
    ]
