# Generated by Django 4.0.3 on 2022-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_remove_client_pub_date_remove_enddate_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_text', models.CharField(max_length=200)),
                ('client_text', models.CharField(max_length=200)),
                ('promotype_text', models.CharField(max_length=200)),
                ('promovolume_text', models.CharField(max_length=200)),
                ('promodiscount_text', models.CharField(max_length=200)),
                ('startdate_text', models.CharField(max_length=200)),
                ('enddate_text', models.CharField(max_length=200)),
                ('percentthismonth_text', models.CharField(max_length=200)),
                ('percentnextmonth_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='EndDate',
        ),
        migrations.DeleteModel(
            name='PercentNextMonth',
        ),
        migrations.DeleteModel(
            name='PercentThisMonth',
        ),
        migrations.DeleteModel(
            name='PromoDiscount',
        ),
        migrations.DeleteModel(
            name='PromoType',
        ),
        migrations.DeleteModel(
            name='PromoVolume',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.DeleteModel(
            name='StartDate',
        ),
    ]
