# Generated by Django 4.0.3 on 2022-04-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_promo_delete_client_delete_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='client_text',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='enddate_text',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='percentnextmonth_text',
            new_name='percent_next_month',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='percentthismonth_text',
            new_name='percent_this_month',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='promodiscount_text',
            new_name='promo_discount',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='promotype_text',
            new_name='promo_type',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='promovolume_text',
            new_name='promo_volume',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='sku_text',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='startdate_text',
            new_name='start_date',
        ),
    ]
