version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./PromoCRM:/app
    command: sh -c "python manage.py runserver 127.0.0.1:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=0.0.0.0