version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-p0p$z(d0y-3abu6to0po-r+yg04cd6(f5ziw63#v56&4kuy(i!
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=1
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data: