version: '3.8'

services:
  app:
    build:
      context: .
    command: python manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DEBUG=1